I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 41, in script
    jump get_up
ScriptError: could not find label 'get_up'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 41, in script
    jump get_up
  File "E:\IDMDownload\renpy-8.3.2-sdk\renpy\ast.py", line 1699, in execute
    rv = renpy.game.script.lookup(target)
  File "E:\IDMDownload\renpy-8.3.2-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'get_up'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.3.2.24090902
the_endless_day_in_ECNU 1.0
Fri Nov  8 20:45:31 2024
